"""
QVC Phase 2 Test Suite

QKD Pipeline Tests:
  WP #646: BB84 basis selection randomness
  WP #647: Key sifting correctness
  WP #648: Error rate estimation accuracy
  WP #649: Privacy amplification output
  WP #650: Real-time key exchange status UI

Encryption System Tests:
  WP #651: SRTP key integration from QKD
  WP #652: FileKeyGenerator resource management
  WP #653: Encryption at rest for stored keys

Streaming Tests:
  WP #654: WebRTC peer connection lifecycle
  WP #655: Video stream quality and codec negotiation
  WP #656: Text chat message delivery

Frontend Tests:
  WP #657: Electron app launch and window management
  WP #658: React component render and state management
  WP #659: Camera/microphone permission handling

Room Management Tests:
  WP #660: Room creation and join flow
  WP #661: Session cleanup and resource release
"""
import os
import re
import tempfile
import hashlib
import pytest
from collections import Counter
from unittest.mock import MagicMock, patch, PropertyMock

from shared.encryption import (
    AESEncryption,
    XOREncryption,
    DebugEncryption,
    RandomKeyGenerator,
    FileKeyGenerator,
    DebugKeyGenerator,
    create_encrypt_scheme,
    create_key_generator,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def _read_source(relative_path: str) -> str:
    """Read a source file relative to the QVC project root."""
    full = os.path.join(_PROJECT_ROOT, relative_path)
    assert os.path.exists(full), f"Source file not found: {full}"
    with open(full) as f:
        return f.read()


# ===================================================================
# QKD Pipeline Tests
# ===================================================================


class TestBB84BasisSelectionRandomness:
    """WP #646: BB84 basis selection randomness.

    The QKD pipeline relies on random key material generated by
    RandomKeyGenerator. These tests verify that the output has the
    statistical properties expected of a good random source (uniform
    distribution, non-repeating, sufficient entropy).
    """

    def test_random_keys_are_unique(self):
        """Consecutive key generations must produce distinct keys."""
        gen = RandomKeyGenerator(key_length=128)
        keys = set()
        for _ in range(100):
            gen.generate_key()
            keys.add(gen.get_key())
        # All 100 keys must be unique (collision probability ~0)
        assert len(keys) == 100

    def test_bit_distribution_is_uniform(self):
        """Aggregate bit counts across many keys should be roughly 50/50."""
        gen = RandomKeyGenerator(key_length=256)
        ones = 0
        total_bits = 0
        for _ in range(500):
            gen.generate_key()
            key = gen.get_key()
            for byte in key:
                ones += bin(byte).count('1')
                total_bits += 8
        ratio = ones / total_bits
        # Allow 3% deviation from ideal 0.5
        assert 0.47 <= ratio <= 0.53, f"Bit ratio {ratio:.4f} outside acceptable range"

    def test_basis_selection_simulated_uniformity(self):
        """Simulate BB84 basis selection using random bytes and verify
        that both bases appear with near-equal probability."""
        gen = RandomKeyGenerator(key_length=1024)
        gen.generate_key()
        raw = gen.get_key()
        # Treat each bit as a basis choice: 0 = rectilinear, 1 = diagonal
        basis_choices = []
        for byte in raw:
            for bit in range(8):
                basis_choices.append((byte >> bit) & 1)
        counts = Counter(basis_choices)
        total = len(basis_choices)
        ratio = counts[0] / total
        assert 0.45 <= ratio <= 0.55, f"Basis ratio {ratio:.4f} is not sufficiently uniform"

    def test_key_length_matches_request(self):
        """Generated key byte count should match ceil(key_length / 8)."""
        for bits in (64, 128, 256, 512):
            gen = RandomKeyGenerator(key_length=bits)
            gen.generate_key()
            expected_bytes = (bits + 7) // 8
            assert len(gen.get_key()) == expected_bytes

    def test_os_urandom_is_source(self):
        """RandomKeyGenerator should delegate to os.urandom."""
        gen = RandomKeyGenerator(key_length=128)
        with patch('shared.encryption.os.urandom', return_value=b'\xaa' * 16) as mock_ur:
            gen.generate_key()
            mock_ur.assert_called_once_with(16)
            assert gen.get_key() == b'\xaa' * 16


class TestKeySiftingCorrectness:
    """WP #647: Key sifting correctness.

    After BB84 basis reconciliation, only matching-basis bits should be
    retained. Since the actual QKD protocol is not yet integrated, these
    tests verify the underlying primitives: key material can be bitwise
    masked and the surviving bits match expectations.
    """

    def test_bitwise_mask_retains_correct_positions(self):
        """Sifting mask applied to raw key retains only marked positions."""
        raw_key = bytes([0b10110100, 0b11001010])
        mask = bytes([0b11110000, 0b00001111])
        sifted = bytes(a & m for a, m in zip(raw_key, mask))
        assert sifted == bytes([0b10110000, 0b00001010])

    def test_sifted_key_shorter_than_raw(self):
        """After sifting, the effective key entropy is roughly half
        the raw bits (assuming 50% basis match rate)."""
        gen = RandomKeyGenerator(key_length=256)
        gen.generate_key()
        raw_key = gen.get_key()
        # Simulate 50% sifting — keep every other byte
        sifted = raw_key[::2]
        assert len(sifted) == len(raw_key) // 2

    def test_empty_mask_yields_zero_key(self):
        """An all-zero mask should produce an all-zero sifted key."""
        raw = bytes([0xFF] * 16)
        mask = bytes([0x00] * 16)
        sifted = bytes(a & m for a, m in zip(raw, mask))
        assert sifted == bytes(16)

    def test_full_mask_preserves_entire_key(self):
        """An all-one mask should preserve the raw key exactly."""
        raw = os.urandom(16)
        mask = bytes([0xFF] * 16)
        sifted = bytes(a & m for a, m in zip(raw, mask))
        assert sifted == raw


class TestErrorRateEstimation:
    """WP #648: Error rate estimation accuracy.

    QBER (Quantum Bit Error Rate) should be accurately computed from
    comparison samples. The encryption roundtrip must have zero error
    rate for valid keys, and tampered ciphertext must be detected.
    """

    def _compute_qber(self, bits_a, bits_b):
        """Compute bit error rate between two byte sequences."""
        total = 0
        errors = 0
        for a, b in zip(bits_a, bits_b):
            for bit in range(8):
                total += 1
                if ((a >> bit) & 1) != ((b >> bit) & 1):
                    errors += 1
        return errors / total if total else 0.0

    def test_identical_sequences_zero_qber(self):
        data = os.urandom(32)
        assert self._compute_qber(data, data) == 0.0

    def test_fully_flipped_qber_is_one(self):
        data = os.urandom(32)
        flipped = bytes(b ^ 0xFF for b in data)
        assert self._compute_qber(data, flipped) == 1.0

    def test_single_bit_flip_low_qber(self):
        data = bytearray(os.urandom(32))
        corrupted = bytearray(data)
        corrupted[0] ^= 0x01  # flip one bit
        qber = self._compute_qber(bytes(data), bytes(corrupted))
        assert 0 < qber < 0.01  # one bit out of 256

    def test_aes_roundtrip_zero_error_rate(self):
        """AES encrypt-then-decrypt should have zero QBER."""
        enc = AESEncryption()
        key = os.urandom(16)
        plaintext = os.urandom(64)
        ct = enc.encrypt(plaintext, key)
        recovered = enc.decrypt(ct, key)
        assert self._compute_qber(plaintext, recovered) == 0.0

    def test_threshold_detection(self):
        """QBER above 11% should trigger abort (BB84 security threshold)."""
        data = bytearray(os.urandom(100))
        corrupted = bytearray(data)
        # Flip ~15% of bits
        for i in range(0, len(data), 6):
            corrupted[i] ^= 0xFF
        qber = self._compute_qber(bytes(data), bytes(corrupted))
        assert qber > 0.11, f"QBER {qber:.4f} should exceed BB84 threshold"


class TestPrivacyAmplification:
    """WP #649: Privacy amplification output.

    Privacy amplification compresses the sifted key to eliminate any
    information an eavesdropper may have. We verify that hash-based
    compression produces keys of the correct length and that different
    inputs produce different outputs.
    """

    def _amplify(self, sifted_key: bytes, output_bits: int = 128) -> bytes:
        """Simple hash-based privacy amplification."""
        h = hashlib.sha256(sifted_key).digest()
        return h[: output_bits // 8]

    def test_output_length(self):
        sifted = os.urandom(32)
        amplified = self._amplify(sifted, 128)
        assert len(amplified) == 16

    def test_different_inputs_different_outputs(self):
        a = self._amplify(b'key_material_A_padding_1234567!')
        b = self._amplify(b'key_material_B_padding_1234567!')
        assert a != b

    def test_deterministic_for_same_input(self):
        key = os.urandom(32)
        assert self._amplify(key) == self._amplify(key)

    def test_amplified_key_usable_for_aes(self):
        """Privacy-amplified key should be a valid AES-128 key."""
        sifted = os.urandom(32)
        aes_key = self._amplify(sifted, 128)
        enc = AESEncryption()
        ct = enc.encrypt(b'test data 123456', aes_key)
        assert enc.decrypt(ct, aes_key) == b'test data 123456'

    def test_entropy_reduction(self):
        """Output should be shorter than input (compression)."""
        sifted = os.urandom(64)  # 512 bits in
        amplified = self._amplify(sifted, 128)  # 128 bits out
        assert len(amplified) < len(sifted)


class TestRealTimeKeyExchangeStatusUI:
    """WP #650: Real-time key exchange status UI.

    The frontend receives key exchange status via socket events.
    Verify the source files contain the proper event listeners and
    status structures.
    """

    def test_connection_status_component_exists(self):
        path = os.path.join(_PROJECT_ROOT, 'frontend', 'src', 'renderer',
                            'components', 'ConnectionStatus.tsx')
        assert os.path.exists(path)

    def test_connection_status_has_server_states(self):
        src = _read_source('frontend/src/renderer/components/ConnectionStatus.tsx')
        assert "'connecting'" in src or '"connecting"' in src
        assert "'connected'" in src or '"connected"' in src
        assert "'error'" in src or '"error"' in src

    def test_connection_status_exports_conn_status_type(self):
        src = _read_source('frontend/src/renderer/components/ConnectionStatus.tsx')
        assert 'ConnStatus' in src
        assert 'export' in src

    def test_client_context_exposes_server_connected(self):
        src = _read_source('frontend/src/renderer/utils/ClientContext.tsx')
        assert 'serverConnected' in src
        assert 'middlewareConnected' in src

    def test_use_connection_hook_has_status_events(self):
        src = _read_source('frontend/src/renderer/hooks/useConnection.ts')
        assert "'connect'" in src or '"connect"' in src
        assert "'disconnect'" in src or '"disconnect"' in src
        assert "'server-connected'" in src or '"server-connected"' in src

    def test_status_widget_exists(self):
        path = os.path.join(_PROJECT_ROOT, 'frontend', 'src', 'renderer',
                            'components', 'widgets', 'StatusWidget.tsx')
        assert os.path.exists(path)


# ===================================================================
# Encryption System Tests
# ===================================================================


class TestSRTPKeyIntegration:
    """WP #651: SRTP key integration from QKD.

    The AV pipeline uses encryption keys from the key generator for
    encrypting media streams. These tests verify the key flows from
    generator -> AV encryption.
    """

    def test_key_rotation_wire_format(self):
        """Wire format is 4-byte key index + encrypted payload."""
        enc = AESEncryption()
        key = os.urandom(16)
        key_idx = 7
        plaintext = b'audio frame data'
        ct = enc.encrypt(plaintext, key)
        wire = key_idx.to_bytes(4, 'big') + ct
        # Parse
        parsed_idx = int.from_bytes(wire[:4], 'big')
        parsed_ct = wire[4:]
        assert parsed_idx == 7
        assert enc.decrypt(parsed_ct, key) == plaintext

    def test_key_generator_produces_aes_compatible_key(self):
        """RandomKeyGenerator(128) should produce 16-byte key usable by AES."""
        gen = RandomKeyGenerator(key_length=128)
        gen.generate_key()
        key = gen.get_key()
        assert len(key) == 16
        enc = AESEncryption()
        ct = enc.encrypt(b'stream payload!!', key)
        assert enc.decrypt(ct, key) == b'stream payload!!'

    def test_encrypt_scheme_registry(self):
        """AES, XOR, DEBUG are all registered in the factory."""
        aes = create_encrypt_scheme('AES')
        xor = create_encrypt_scheme('XOR')
        dbg = create_encrypt_scheme('DEBUG')
        assert isinstance(aes, AESEncryption)
        assert isinstance(xor, XOREncryption)
        assert isinstance(dbg, DebugEncryption)

    def test_invalid_scheme_raises(self):
        with pytest.raises(ValueError, match="Invalid encryption scheme"):
            create_encrypt_scheme('NONEXISTENT')

    def test_key_gen_registry(self):
        """FILE, RANDOM, DEBUG generators are all registered."""
        for name, cls in [('FILE', FileKeyGenerator),
                          ('RANDOM', RandomKeyGenerator),
                          ('DEBUG', DebugKeyGenerator)]:
            gen = create_key_generator(name)
            assert isinstance(gen, cls)

    def test_av_module_uses_key_lock(self):
        """The AV module should use a lock around key access for thread safety."""
        src = _read_source('middleware/client/av.py')
        assert '_key_lock' in src
        assert 'Lock' in src

    def test_av_module_rotates_keys(self):
        """The AV module should have a key rotation thread."""
        src = _read_source('middleware/client/av.py')
        assert '_rotate_keys' in src or 'generate_key' in src
        assert 'Thread' in src


class TestFileKeyGeneratorResourceManagement:
    """WP #652: FileKeyGenerator resource management."""

    def test_context_manager_closes_file(self):
        """FileKeyGenerator should close the file handle on __exit__."""
        with tempfile.NamedTemporaryFile(delete=False) as f:
            f.write(os.urandom(256))
            tmpname = f.name
        try:
            with FileKeyGenerator(file_name=tmpname, key_length=128) as gen:
                gen.generate_key()
                key = gen.get_key()
                assert len(key) == 16
            # After exiting, the file should be closed
            assert gen._file is None
        finally:
            os.unlink(tmpname)

    def test_explicit_close(self):
        with tempfile.NamedTemporaryFile(delete=False) as f:
            f.write(os.urandom(256))
            tmpname = f.name
        try:
            gen = FileKeyGenerator(file_name=tmpname, key_length=128)
            gen.generate_key()
            assert gen._file is not None
            gen.close()
            assert gen._file is None
        finally:
            os.unlink(tmpname)

    def test_double_close_is_safe(self):
        with tempfile.NamedTemporaryFile(delete=False) as f:
            f.write(os.urandom(256))
            tmpname = f.name
        try:
            gen = FileKeyGenerator(file_name=tmpname, key_length=128)
            gen.generate_key()
            gen.close()
            gen.close()  # Should not raise
            assert gen._file is None
        finally:
            os.unlink(tmpname)

    def test_missing_file_raises(self):
        gen = FileKeyGenerator(file_name='/tmp/nonexistent_qvc_key_file.bin',
                               key_length=128)
        with pytest.raises(FileNotFoundError):
            gen.generate_key()

    def test_zero_key_length_raises(self):
        gen = FileKeyGenerator(key_length=0)
        with pytest.raises(ValueError, match="nonzero"):
            gen.generate_key()

    def test_del_closes_file(self):
        """__del__ should close the file handle to prevent leaks."""
        with tempfile.NamedTemporaryFile(delete=False) as f:
            f.write(os.urandom(256))
            tmpname = f.name
        try:
            gen = FileKeyGenerator(file_name=tmpname, key_length=128)
            gen.generate_key()
            file_obj = gen._file
            assert not file_obj.closed
            gen.__del__()
            assert file_obj.closed
        finally:
            os.unlink(tmpname)


class TestEncryptionAtRest:
    """WP #653: Encryption at rest for stored keys.

    Verify that key material on disk is protected, config does not
    leak secrets, and encryption defaults are secure.
    """

    def test_default_encrypt_scheme_is_aes(self):
        src = _read_source('shared/config.py')
        assert "encrypt_scheme: str = 'AES'" in src or 'encrypt_scheme.*AES' in src

    def test_default_key_length_is_128(self):
        src = _read_source('shared/config.py')
        assert 'key_length: int = 128' in src

    def test_config_no_plaintext_secrets(self):
        """Config source should not contain hardcoded encryption keys."""
        src = _read_source('shared/config.py')
        # Should not contain hex key patterns like 0x followed by 16+ hex chars
        long_hex = re.findall(r'0x[0-9a-fA-F]{32,}', src)
        assert len(long_hex) == 0, f"Potential hardcoded key found: {long_hex}"

    def test_aes_ciphertext_is_not_plaintext(self):
        enc = AESEncryption()
        key = os.urandom(16)
        plaintext = b'sensitive key mat'
        ct = enc.encrypt(plaintext, key)
        assert plaintext not in ct

    def test_random_key_not_deterministic(self):
        """Two RandomKeyGenerator instances should produce different keys."""
        gen1 = RandomKeyGenerator(key_length=128)
        gen2 = RandomKeyGenerator(key_length=128)
        gen1.generate_key()
        gen2.generate_key()
        assert gen1.get_key() != gen2.get_key()


# ===================================================================
# Streaming Tests
# ===================================================================


class TestWebRTCPeerConnectionLifecycle:
    """WP #654: WebRTC peer connection lifecycle.

    The peer connection lifecycle is managed by PeerConnectionManager
    on the server side and Client on the middleware side.
    """

    def test_peer_manager_module_exists(self):
        path = os.path.join(_PROJECT_ROOT, 'server', 'peer_manager.py')
        assert os.path.exists(path)

    def test_peer_manager_has_connect_and_disconnect(self):
        src = _read_source('server/peer_manager.py')
        assert 'def connect(' in src
        assert 'def disconnect(' in src

    def test_self_connection_prevented(self):
        """PeerConnectionManager source should reject self-connections."""
        src = _read_source('server/peer_manager.py')
        assert 'user_id == peer_id' in src

    def test_client_has_peer_connection_handler(self):
        src = _read_source('middleware/client/client.py')
        assert 'handle_peer_connection' in src
        assert 'disconnect_from_peer' in src

    def test_client_states_include_connected(self):
        from shared.state import ClientState
        assert hasattr(ClientState, 'CONNECTED')
        assert hasattr(ClientState, 'NEW')
        assert hasattr(ClientState, 'LIVE')

    def test_socket_client_has_connect_disconnect(self):
        src = _read_source('middleware/client/socket_client.py')
        assert 'def connect(' in src
        assert 'def disconnect(' in src
        assert 'def is_connected(' in src

    def test_peer_disconnect_notifies_adapter(self):
        """Client should notify the frontend adapter on peer disconnect."""
        src = _read_source('middleware/client/client.py')
        assert "send_status('peer_disconnected'" in src


class TestVideoStreamQuality:
    """WP #655: Video stream quality and codec negotiation.

    The AV pipeline uses ffmpeg for codec negotiation (libx264, ismv format).
    """

    def test_video_namespace_uses_ffmpeg(self):
        src = _read_source('shared/av/namespaces.py')
        assert 'ffmpeg' in src

    def test_video_codec_is_x264(self):
        src = _read_source('shared/av/namespaces.py')
        assert 'libx264' in src

    def test_video_namespace_uses_zerolatency(self):
        """Codec should use zerolatency tune for real-time streaming."""
        src = _read_source('shared/av/namespaces.py')
        assert 'zerolatency' in src

    def test_video_namespace_uses_ultrafast_preset(self):
        src = _read_source('shared/av/namespaces.py')
        assert 'ultrafast' in src

    def test_default_video_dimensions(self):
        src = _read_source('shared/config.py')
        assert 'video_width: int = 640' in src
        assert 'video_height: int = 480' in src

    def test_default_frame_rate(self):
        src = _read_source('shared/config.py')
        assert 'frame_rate: int = 15' in src

    def test_default_display_dimensions(self):
        src = _read_source('shared/config.py')
        assert 'display_width: int = 960' in src
        assert 'display_height: int = 720' in src


class TestTextChatMessageDelivery:
    """WP #656: Text chat message delivery."""

    def test_chat_component_exists(self):
        path = os.path.join(_PROJECT_ROOT, 'frontend', 'src', 'renderer',
                            'components', 'chat', 'Chat.tsx')
        assert os.path.exists(path)

    def test_chat_has_send_handler(self):
        src = _read_source('frontend/src/renderer/components/chat/Chat.tsx')
        assert 'handleSend' in src
        assert 'handleSubmit' in src

    def test_chat_has_message_interface(self):
        src = _read_source('frontend/src/renderer/components/chat/Chat.tsx')
        assert 'interface MessageData' in src or 'interface ChatProps' in src
        assert 'time' in src
        assert 'name' in src
        assert 'body' in src

    def test_message_component_exists(self):
        path = os.path.join(_PROJECT_ROOT, 'frontend', 'src', 'renderer',
                            'components', 'chat', 'Message.tsx')
        assert os.path.exists(path)

    def test_client_context_has_chat(self):
        src = _read_source('frontend/src/renderer/utils/ClientContext.tsx')
        assert 'chat' in src
        assert 'sendMessage' in src
        assert 'messages' in src

    def test_socket_client_has_send_message(self):
        src = _read_source('middleware/client/socket_client.py')
        assert 'def send_message(' in src


# ===================================================================
# Frontend Tests
# ===================================================================


class TestElectronAppLaunchAndWindowManagement:
    """WP #657: Electron app launch and window management."""

    def test_main_ts_exists(self):
        path = os.path.join(_PROJECT_ROOT, 'frontend', 'src', 'main', 'main.ts')
        assert os.path.exists(path)

    def test_creates_browser_window(self):
        src = _read_source('frontend/src/main/main.ts')
        assert 'BrowserWindow' in src
        assert 'new BrowserWindow' in src

    def test_window_dimensions_set(self):
        src = _read_source('frontend/src/main/main.ts')
        assert 'width:' in src or 'width =' in src
        assert 'height:' in src or 'height =' in src

    def test_context_isolation_enabled(self):
        """Security: contextIsolation should be true."""
        src = _read_source('frontend/src/main/main.ts')
        assert 'contextIsolation: true' in src

    def test_node_integration_disabled(self):
        """Security: nodeIntegration should be false."""
        src = _read_source('frontend/src/main/main.ts')
        assert 'nodeIntegration: false' in src

    def test_ready_to_show_handler(self):
        src = _read_source('frontend/src/main/main.ts')
        assert 'ready-to-show' in src

    def test_window_closed_handler(self):
        src = _read_source('frontend/src/main/main.ts')
        assert "'closed'" in src or '"closed"' in src

    def test_spawns_python_middleware(self):
        """Electron main should spawn the Python middleware process."""
        src = _read_source('frontend/src/main/main.ts')
        assert 'spawn' in src
        assert 'python' in src.lower() or 'video_chat.py' in src


class TestReactComponentRenderAndState:
    """WP #658: React component render and state management."""

    def test_app_tsx_exists(self):
        path = os.path.join(_PROJECT_ROOT, 'frontend', 'src', 'renderer', 'App.tsx')
        assert os.path.exists(path)

    def test_app_uses_client_context_provider(self):
        src = _read_source('frontend/src/renderer/App.tsx')
        assert 'ClientContextProvider' in src

    def test_main_screen_uses_context(self):
        src = _read_source('frontend/src/renderer/screens/MainScreen.tsx')
        assert 'useContext' in src
        assert 'ClientContext' in src

    def test_main_screen_conditional_render(self):
        """MainScreen should render Lobby or InCall based on session state."""
        src = _read_source('frontend/src/renderer/screens/MainScreen.tsx')
        assert 'Lobby' in src
        assert 'InCall' in src
        assert 'roomId' in src or 'inSession' in src

    def test_client_context_provides_all_state(self):
        src = _read_source('frontend/src/renderer/utils/ClientContext.tsx')
        required_fields = [
            'middlewareConnected', 'serverConnected', 'userId',
            'roomId', 'cameraOn', 'muted', 'waitingForPeer',
            'errorMessage',
        ]
        for field in required_fields:
            assert field in src, f"Missing context field: {field}"

    def test_hooks_use_dependency_injection(self):
        """Hooks should accept socket factories for testability."""
        for hook_file in ('useConnection.ts', 'useSession.ts', 'useMedia.ts'):
            src = _read_source(f'frontend/src/renderer/hooks/{hook_file}')
            # Should accept an optional factory/provider parameter
            assert 'socketFactory' in src or 'socketProvider' in src, \
                f"{hook_file} missing socket injection parameter"

    def test_video_player_component_exists(self):
        src = _read_source('frontend/src/renderer/components/VideoPlayer.tsx')
        assert 'VideoPlayer' in src
        assert 'srcObject' in src


class TestCameraMicrophonePermissionHandling:
    """WP #659: Camera/microphone permission handling."""

    def test_use_media_hook_exists(self):
        path = os.path.join(_PROJECT_ROOT, 'frontend', 'src', 'renderer',
                            'hooks', 'useMedia.ts')
        assert os.path.exists(path)

    def test_use_media_has_toggle_camera(self):
        src = _read_source('frontend/src/renderer/hooks/useMedia.ts')
        assert 'toggleCamera' in src
        assert 'toggleMute' in src

    def test_use_media_has_device_selection(self):
        src = _read_source('frontend/src/renderer/hooks/useMedia.ts')
        assert 'selectCamera' in src
        assert 'refreshCameras' in src

    def test_use_media_emits_toggle_events(self):
        src = _read_source('frontend/src/renderer/hooks/useMedia.ts')
        assert "'toggle_camera'" in src or '"toggle_camera"' in src
        assert "'toggle_mute'" in src or '"toggle_mute"' in src

    def test_use_media_has_audio_device_support(self):
        src = _read_source('frontend/src/renderer/hooks/useMedia.ts')
        assert 'audioDevices' in src or 'AudioDevice' in src
        assert 'selectAudio' in src

    def test_video_chat_handles_mute_toggle(self):
        """Middleware entrypoint should handle toggle_mute from frontend."""
        src = _read_source('middleware/video_chat.py')
        assert 'toggle_mute' in src

    def test_camera_off_shows_noise_canvas(self):
        """VideoPlayer should show NoiseCanvas when camera is disabled."""
        src = _read_source('frontend/src/renderer/components/VideoPlayer.tsx')
        assert 'NoiseCanvas' in src
        assert 'cameraEnabled' in src


# ===================================================================
# Room Management Tests
# ===================================================================


class TestRoomCreationAndJoinFlow:
    """WP #660: Room creation and join flow."""

    def test_use_session_hook_exists(self):
        path = os.path.join(_PROJECT_ROOT, 'frontend', 'src', 'renderer',
                            'hooks', 'useSession.ts')
        assert os.path.exists(path)

    def test_use_session_has_join_and_leave(self):
        src = _read_source('frontend/src/renderer/hooks/useSession.ts')
        assert 'joinRoom' in src
        assert 'leaveRoom' in src

    def test_use_session_emits_socket_events(self):
        src = _read_source('frontend/src/renderer/hooks/useSession.ts')
        assert "'join_room'" in src or '"join_room"' in src
        assert "'leave_room'" in src or '"leave_room"' in src

    def test_use_session_handles_room_id(self):
        src = _read_source('frontend/src/renderer/hooks/useSession.ts')
        assert "'room-id'" in src or '"room-id"' in src
        assert 'setRoomId' in src or '_setRoomId' in src

    def test_use_session_handles_waiting_for_peer(self):
        src = _read_source('frontend/src/renderer/hooks/useSession.ts')
        assert "'waiting-for-peer'" in src or '"waiting-for-peer"' in src
        assert 'waitingForPeer' in src

    def test_server_has_peer_connection_manager(self):
        src = _read_source('server/peer_manager.py')
        assert 'class PeerConnectionManager' in src

    def test_client_has_connect_to_peer(self):
        """video_chat.py should wire adapter.on_peer_id to client.connect_to_peer."""
        src = _read_source('middleware/video_chat.py')
        assert 'connect_to_peer' in src

    def test_join_room_handles_errors(self):
        src = _read_source('frontend/src/renderer/hooks/useSession.ts')
        assert 'setErrorMessage' in src or 'error' in src.lower()


class TestSessionCleanupAndResourceRelease:
    """WP #661: Session cleanup and resource release."""

    def test_client_kill_closes_api_and_websocket(self):
        src = _read_source('middleware/client/client.py')
        assert 'def kill(' in src
        assert 'api_instance' in src
        assert 'websocket_instance' in src

    def test_disconnect_from_peer_stops_key_rotation(self):
        """Disconnecting should stop the key rotation thread."""
        src = _read_source('middleware/client/client.py')
        assert '_key_stop' in src

    def test_disconnect_resets_state_to_live(self):
        src = _read_source('middleware/client/client.py')
        assert 'ClientState.LIVE' in src

    def test_peer_manager_disconnect_resets_both_users(self):
        """Server-side disconnect should reset both user and peer to IDLE."""
        src = _read_source('server/peer_manager.py')
        assert 'IDLE' in src

    def test_server_has_graceful_shutdown(self):
        src = _read_source('server/main.py')
        assert 'graceful_shutdown' in src or '_shutdown' in src

    def test_signal_handlers_registered(self):
        """Server main should register SIGINT and SIGTERM handlers."""
        src = _read_source('server/main.py')
        assert 'SIGINT' in src
        assert 'SIGTERM' in src

    def test_electron_before_quit_kills_python(self):
        """Electron should kill Python process on before-quit."""
        src = _read_source('frontend/src/main/main.ts')
        assert 'before-quit' in src
        assert 'kill' in src

    def test_file_key_generator_cleanup_on_del(self):
        """FileKeyGenerator.__del__ should close the file handle."""
        src = _read_source('shared/encryption.py')
        assert 'def __del__(' in src
        assert 'self.close()' in src

    def test_video_chat_finally_cleanup(self):
        """video_chat.py should disconnect in a finally block."""
        src = _read_source('middleware/video_chat.py')
        assert 'finally:' in src
        assert 'disconnect' in src
